title:		Beyond Venice
description:	'A survey of the Beyond Baroque archive and its networks.'
freetext:  By Dylan Karlsson
baseurl:	'/'
paginate:	0
version:	0.1.0
colorscheme:	scheme-custom

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

author:
 url:
 name:

github:
 repo:		https://github.com/dylkarlsson/beyondvenice

gems:		[jekyll-paginate]

exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem']
