title:		Beyond Venice
description:	'A survey of the Beyond Baroque archive and its networks.'
freetext:  Project by Dylan Karlsson.
baseurl:	'/'
paginate:	5
version:	0.1.0
colorscheme:	scheme-custom

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

author:
 url:		https://dylankarlsson.github.io/bb-networks/#/
 name:		'Networks'

github:
 repo:		https://github.com/dylkarlsson/beyondvenice

gems:		[jekyll-paginate]

exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem']
