
##
# RLStevenson Theme Options
####

# For baseurl:
# Use '' for / or '/your-dir' for another directory

title:		BeyondVenice
description:	'A survey of the Beyond Baroque archive and its networks.'
freetext:	'Created for Miriam Posner's Digital Humanities 201 class.'
baseurl:	'/'
paginate:	3
version:	0.1.0
colorscheme:	scheme-custom

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

author:
 url:		http://www.beyondbaroque.org/
 name:		'Beyond Baroque'

github:
 repo:		https://github.com/ExchangeRate-API/rlstevenson-jekyll-theme

gems:		[jekyll-paginate]

exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem']
